---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./descheduler/ks.yaml
  - ./hcloud-csi/ks.yaml
  - ./hcloud-ccm/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./talos-ccm/ks.yaml