---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-witl-xyz
spec:
  dnsNames:
    - cloud.witl.xyz
    - "*.cloud.witl.xyz"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  renewBefore: 48h
  secretName: cloud-witl-xyz-tls
  usages:
    - digital signature
    - server auth