---
# Backend for Duo SSO JWKS (remote JWT key fetch). Required so Envoy has a cluster
# for https://sso-3da0e7d4.sso.duosecurity.com when using SecurityPolicy remoteJWKS.
# See: https://gateway.envoyproxy.io/docs/tasks/security/jwt-authentication/#connect-to-a-remote-jwks
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: duo-jwks
spec:
  endpoints:
    - fqdn:
        hostname: sso-3da0e7d4.sso.duosecurity.com
        port: 443
