---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend-duo-jwks.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./security-policy.yaml
  - ./write-security-policy.yaml
