---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
spec:
  chart:
    spec:
      chart: hcloud-csi
      version: "2.19.0"
      sourceRef:
        kind: HelmRepository
        name: hcloud-csi
      interval: 15m
  interval: 1h
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      hcloudToken:
        value: ""
        existingSecret:
          name: hcloud-csi
          key: token
      hcloudVolumeDefaultLocation: "fsn1"
    node:
      kubeletDir: /var/lib/kubelet
      affinity: {}
    storageClasses:
      - name: hcloud-volumes
        defaultStorageClass: true
        reclaimPolicy: Delete
