---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: cloud-ops
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account
          key: token
          namespace: external-secrets
      # Reduce API calls to avoid 1Password rate limits
      cache:
        ttl: 30m
        maxSize: 100