---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
spec:
  chartRef:
    kind: OCIRepository
    name: talos-cloud-controller-manager
  interval: 1h
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    enabledControllers:
      - "*"