---
# Example Certificate for the cluster wildcard domain
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rackspace-wildcard-tls
  namespace: network
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.rackspace.example.com"
  dnsNames:
    - "rackspace.example.com"
    - "*.rackspace.example.com"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
