---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# Creates Secret "hcloud" with key "token" for hcloud-csi. Adjust remoteRef to your 1Password item.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud-ccm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hcloud-ccm
    template:
      data:
        token: '{{ .HCLOUD_TOKEN }}'
        network: '{{ .HCLOUD_NETWORK }}'
  dataFrom:
    - extract:
        key: hcloud