---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hccm
spec:
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: hcloud-ccm
      interval: 15m
  interval: 1h
  targetNamespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    env:
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hcloud-ccm
            key: token
    monitoring:
      enabled: true
      podMonitor:
        enabled: true